cache:
  paths:
    - vendor/
variables:
  DOCKER_IMAGE_COMPOSER_74: registry.local.invbox.ru/invoicebox/infrastructure/infrastructure/composer:7.4
  DOCKER_IMAGE_COMPOSER_80: registry.local.invbox.ru/invoicebox/infrastructure/infrastructure/composer:8.0
  DOCKER_IMAGE_COMPOSER_81: registry.local.invbox.ru/invoicebox/infrastructure/infrastructure/composer:8.1
  DOCKER_IMAGE_COMPOSER_82: registry.local.invbox.ru/invoicebox/infrastructure/infrastructure/composer:8.2
  DOCKER_IMAGE_COMPOSER_83: registry.local.invbox.ru/invoicebox/infrastructure/infrastructure/composer:8.3


stages:
  - lint
  - test
  - deploy

.run_tests: &run_tests
  - eval `ssh-agent -s`
  - ssh-add <(echo "$COMPOSER_SSH_KEY")
  - composer config --global gitlab-token.gitlab.srv.local.invbox.ru $COMPOSER_TOKEN
  - composer install --ignore-platform-reqs
  - vendor/bin/ecs check
  - vendor/bin/phpstan
  - vendor/bin/phpunit --log-junit /app/junit.xml

cs_check:
  stage: lint
  only:
    - master
    - merge_requests
  script:
    - composer install --ignore-platform-reqs
    - ./vendor/bin/ecs check

static_analyse:
  stage: lint
  only:
    - master
    - merge_requests
  script:
    - composer install --ignore-platform-reqs
    - vendor/bin/phpstan analyse --memory-limit 512M

test-php-74:
  stage: test
  image: $DOCKER_IMAGE_COMPOSER_74
  only:
    - master
    - merge_requests
  script:
    - *run_tests
  artifacts:
    reports:
      junit: junit.xml

test-php-80:
  stage: test
  image: $DOCKER_IMAGE_COMPOSER_80
  only:
    - master
    - merge_requests
  script:
    - *run_tests
  artifacts:
    reports:
      junit: junit.xml
  
test-php-81:
  stage: test
  image: $DOCKER_IMAGE_COMPOSER_81
  only:
    - master
    - merge_requests
  script:
    - *run_tests
  artifacts:
    reports:
      junit: junit.xml

test-php-82:
  stage: test
  image: $DOCKER_IMAGE_COMPOSER_82
  only:
    - master
    - merge_requests
  script:
    - *run_tests
  artifacts:
    reports:
      junit: junit.xml

test-php-83:
  stage: test
  image: $DOCKER_IMAGE_COMPOSER_83
  only:
    - master
    - merge_requests
  script:
    - *run_tests
  artifacts:
    reports:
      junit: junit.xml


publish:
  only:
    - tags
  stage: deploy
  script:
    - 'curl -sS --show-error --fail --data tag=${CI_COMMIT_TAG} --header "JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/composer"'
